export const FIELDS_NAMES = Object.freeze({
  BODY: 'body',
  MAP: 'map',
  TAG_CATEGORY: 'tagCategory',
  CATEGORY_ITEM: 'categoryItem',
  AUTHORITY: 'authority',
  STATUS: 'status',
  NEWS_FILTER: 'newsFilter',
  RATING: 'rating',
  TAG_CLOUD: 'tagCloud',
  TITLE: 'title',
  DESCRIPTION: 'description',
  NAME: 'name',
  PARENT: 'parent',
  GALLERY_ALBUM: 'galleryAlbum',
  GALLERY_ITEM: 'galleryItem',
  AVATAR: 'avatar',
  WEBSITE: 'website',
  BACKGROUND: 'background',
  ADDRESS: 'address',
  LINK: 'link',
  TAG: 'tag',
  PHONE: 'phone',
  EMAIL: 'email',
  PRICE: 'price',
  BUTTON: 'button',
  WORK_TIME: 'workTime',
  CHART_ID: 'chartid',
  PAGE_CONTENT: 'pageContent',
  LIST_ITEM: 'listItem',
  MENU_ITEM: 'menuItem',
  SORT_CUSTOM: 'sortCustom',
  BLOG: 'blog',
  FORM: 'form',
  COMPANY_ID: 'companyId',
  PRODUCT_ID: 'productId',
  GROUP_ID: 'groupId',
  OPTIONS: 'options',
  AGE_RANGE: 'ageRange',
  PUBLICATION_DATE: 'publicationDate',
  LANGUAGE: 'language',
  WEIGHT: 'productWeight',
  DIMENSIONS: 'dimensions',
  AUTHORS: 'authors',
  PUBLISHER: 'publisher',
  PRINT_LENGTH: 'printLength',
  WIDGET: 'widget',
  NEWS_FEED: 'newsFeed',
  DEPARTMENTS: 'departments',
  MERCHANT: 'merchant',
  MANUFACTURER: 'manufacturer',
  BRAND: 'brand',
  FEATURES: 'features',
  PIN: 'pin',
  REMOVE: 'remove',
  SHOP_FILTER: 'shopFilter',
  RELATED: 'related',
  ADD_ON: 'addOn',
  FEATURED: 'featured',
  SIMILAR: 'similar',
  AFFILIATE_BUTTON: 'affiliateButton',
  AFFILIATE_PRODUCT_ID_TYPES: 'affiliateProductIdTypes',
  AFFILIATE_GEO_AREA: 'affiliateGeoArea',
  AFFILIATE_URL_TEMPLATE: 'affiliateUrlTemplate',
  AFFILIATE_CODE: 'affiliateCode',
  WEB_PAGE: 'webpage',
  MAP_RECTANGLES: 'mapRectangles',
  MAP_OBJECT_TYPES: 'mapObjectTypes',
  MAP_OBJECT_TAGS: 'mapObjectTags',
  MAP_MOBILE_VIEW: 'mapMobileView',
  MAP_DESKTOP_VIEW: 'mapDesktopView',
  MAP_OBJECTS_LIST: 'mapObjectsList',
  WALLET_ADDRESS: 'walletAddress',
  DELEGATION: 'delegation',
  URL: 'url',
  CALORIES: 'calories',
  BUDGET: 'budget',
  COOKING_TIME: 'cookingTime',
  COST: 'cost',
  RECIPE_INGREDIENTS: 'recipeIngredients',
  GROUP_EXPERTISE: 'groupExpertise',
  GROUP_FOLLOWERS: 'groupFollowers',
  GROUP_FOLLOWING: 'groupFollowing',
  GROUP_ADD: 'groupAdd',
  GROUP_EXCLUDE: 'groupExclude',
  PROMOTION: 'promotion',
  GROUP_LAST_ACTIVITY: 'groupLastActivity',
  GROUP_MIN_EXPERTISE: 'groupMinExpertise',
  NUTRITION: 'nutrition',
  SALE: 'sale',
  COMPARE_AT_PRICE: 'compareAtPrice',
  HTML_CONTENT: 'htmlContent',
  CONTENT_POSITION: 'contentPosition',
  CONTENT_VIEW: 'contentView',
} as const);

export const SHOP_SETTINGS_TYPE = Object.freeze({
  USER: 'user',
  OBJECT: 'object',
} as const);

export const ADMIN_ROLES = Object.freeze({
  OWNER: 'owner',
  ADMIN: 'admin',
  OWNERSHIP: 'ownership',
  ADMINISTRATIVE: 'administrative',
  MASTER: 'master',
} as const);

export const VOTE_STATUSES = Object.freeze({
  APPROVED: 'approved',
  REJECTED: 'rejected',
} as const);

export const ARRAY_FIELDS = [
  FIELDS_NAMES.CATEGORY_ITEM,
  FIELDS_NAMES.LIST_ITEM,
  FIELDS_NAMES.TAG_CATEGORY,
  FIELDS_NAMES.GALLERY_ITEM,
  FIELDS_NAMES.GALLERY_ALBUM,
  FIELDS_NAMES.RATING,
  FIELDS_NAMES.BUTTON,
  FIELDS_NAMES.PHONE,
  FIELDS_NAMES.BLOG,
  FIELDS_NAMES.FORM,
  FIELDS_NAMES.NEWS_FILTER,
  FIELDS_NAMES.COMPANY_ID,
  FIELDS_NAMES.PRODUCT_ID,
  FIELDS_NAMES.OPTIONS,
  FIELDS_NAMES.AUTHORS,
  FIELDS_NAMES.DEPARTMENTS,
  FIELDS_NAMES.FEATURES,
  FIELDS_NAMES.AUTHORITY,
  FIELDS_NAMES.GROUP_ID,
  FIELDS_NAMES.PIN,
  FIELDS_NAMES.REMOVE,
  FIELDS_NAMES.MENU_ITEM,
  FIELDS_NAMES.RELATED,
  FIELDS_NAMES.ADD_ON,
  FIELDS_NAMES.FEATURED,
  FIELDS_NAMES.SIMILAR,
  FIELDS_NAMES.AFFILIATE_GEO_AREA,
  FIELDS_NAMES.AFFILIATE_PRODUCT_ID_TYPES,
  FIELDS_NAMES.WALLET_ADDRESS,
  FIELDS_NAMES.DELEGATION,
  FIELDS_NAMES.GROUP_ADD,
  FIELDS_NAMES.GROUP_EXCLUDE,
  FIELDS_NAMES.PROMOTION,
  FIELDS_NAMES.WEBSITE,
];

export const MIN_PERCENT_TO_SHOW_UPDATE = 70;

export const TAG_CLOUDS_UPDATE_COUNT = 5;
export const RATINGS_UPDATE_COUNT = 4;

export const SEARCH_FIELDS = [
  FIELDS_NAMES.NAME,
  FIELDS_NAMES.EMAIL,
  FIELDS_NAMES.PHONE,
  FIELDS_NAMES.ADDRESS,
  FIELDS_NAMES.TITLE,
  FIELDS_NAMES.DESCRIPTION,
  FIELDS_NAMES.CATEGORY_ITEM,
  FIELDS_NAMES.COMPANY_ID,
  FIELDS_NAMES.PRODUCT_ID,
  FIELDS_NAMES.GROUP_ID,
  FIELDS_NAMES.AUTHORS,
  FIELDS_NAMES.PUBLISHER,
  FIELDS_NAMES.BRAND,
  FIELDS_NAMES.MANUFACTURER,
  FIELDS_NAMES.MERCHANT,
  FIELDS_NAMES.RECIPE_INGREDIENTS,
] as const;

export const categorySwitcher: Record<string, string> = {
  galleryAlbum: FIELDS_NAMES.GALLERY_ITEM,
  galleryItem: FIELDS_NAMES.GALLERY_ITEM,
  tagCategory: FIELDS_NAMES.CATEGORY_ITEM,
};

export const INDEPENDENT_FIELDS = [
  FIELDS_NAMES.STATUS,
  FIELDS_NAMES.MAP,
  FIELDS_NAMES.PARENT,
  FIELDS_NAMES.AUTHORITY,
];

export const LANGUAGES_POPULARITY = [
  { lang: 'en-US', score: 1 },
  { lang: 'zh-CN', score: 2 },
  { lang: 'es-ES', score: 3 },
  { lang: 'ar-SA', score: 4 },
  { lang: 'pt-BR', score: 5 },
  { lang: 'ms-MY', score: 6 },
  { lang: 'fr-FR', score: 7 },
  { lang: 'ja-JP', score: 8 },
  { lang: 'ru-RU', score: 9 },
  { lang: 'de-DE', score: 10 },
  { lang: 'uk-UA', score: 11 },
];

export const FULL_SINGLE_FIELDS = [FIELDS_NAMES.NEWS_FEED];

export const STATUSES = Object.freeze({
  RELISTED: 'relisted',
  UNAVAILABLE: 'unavailable',
  NSFW: 'nsfw',
  FLAGGED: 'flagged',
} as const);

export const REMOVE_OBJ_STATUSES = [
  STATUSES.NSFW,
  STATUSES.RELISTED,
  STATUSES.UNAVAILABLE,
];

export const LIST_TYPES = Object.freeze({
  MENU_PAGE: 'menuPage',
  MENU_LIST: 'menuList',
} as const);

export const OBJECT_TYPES = Object.freeze({
  HASHTAG: 'hashtag',
  LIST: 'list',
  PAGE: 'page',
  RESTAURANT: 'restaurant',
  DISH: 'dish',
  DRINK: 'drink',
  BUSINESS: 'business',
  PRODUCT: 'product',
  SERVICE: 'service',
  COMPANY: 'company',
  PERSON: 'person',
  PLACE: 'place',
  CRYPTO: 'crypto',
  HOTEL: 'hotel',
  INDICES: 'indices',
  STOCKS: 'stocks',
  CURRENCIES: 'currencies',
  COMMODITY: 'commodity',
  CAR: 'car',
  TEST: 'test',
  ORGANIZATION: 'organization',
  MOTEL: 'motel',
  RESORT: 'resort',
  BnB: 'b&b',
  BOOK: 'book',
  WIDGET: 'widget',
  NEWS_FEED: 'newsfeed',
  SHOP: 'shop',
  AFFILIATE: 'affiliate',
  WEB_PAGE: 'webpage',
  MAP: 'map',
  LINK: 'link',
  RECIPE: 'recipe',
  GROUP: 'group',
  HTML: 'html',
} as const);

export const CREATE_TAGS_ON_UPDATE_TYPES = [
  OBJECT_TYPES.RESTAURANT,
  OBJECT_TYPES.DRINK,
  OBJECT_TYPES.DISH,
] as const;

export const REQUIREDFIELDS_PARENT = [
  FIELDS_NAMES.NAME,
  FIELDS_NAMES.AVATAR,
  FIELDS_NAMES.MAP,
  FIELDS_NAMES.LIST_ITEM,
  FIELDS_NAMES.SORT_CUSTOM,
];

const MAIN_FIELDS = [
  FIELDS_NAMES.STATUS,
  FIELDS_NAMES.AVATAR,
  FIELDS_NAMES.AUTHORITY,
  FIELDS_NAMES.PIN,
  FIELDS_NAMES.REMOVE,
  FIELDS_NAMES.NAME,
  FIELDS_NAMES.TITLE,
  FIELDS_NAMES.DESCRIPTION,
  FIELDS_NAMES.BACKGROUND,
  FIELDS_NAMES.DELEGATION,
  FIELDS_NAMES.PROMOTION,
];

const MAP_TYPE_FIELDS = [
  FIELDS_NAMES.MAP_RECTANGLES,
  FIELDS_NAMES.MAP_OBJECT_TYPES,
  FIELDS_NAMES.MAP_OBJECT_TAGS,
  FIELDS_NAMES.MAP_MOBILE_VIEW,
  FIELDS_NAMES.MAP_DESKTOP_VIEW,
  FIELDS_NAMES.MAP_OBJECTS_LIST,
];

const CONTACT_FIELDS = [
  FIELDS_NAMES.WORK_TIME,
  FIELDS_NAMES.ADDRESS,
  FIELDS_NAMES.MAP,
  FIELDS_NAMES.WEBSITE,
  FIELDS_NAMES.PHONE,
  FIELDS_NAMES.EMAIL,
  FIELDS_NAMES.LINK,
];

const MENU_FIELDS_LEGACY = [
  FIELDS_NAMES.LIST_ITEM,
  FIELDS_NAMES.MENU_ITEM,
  FIELDS_NAMES.BUTTON,
  FIELDS_NAMES.BLOG,
  FIELDS_NAMES.FORM,
  FIELDS_NAMES.SORT_CUSTOM,
];

const COMMON_FIELDS = [
  ...MAIN_FIELDS,
  ...MENU_FIELDS_LEGACY,
  FIELDS_NAMES.PARENT,
  FIELDS_NAMES.TAG_CATEGORY,
  FIELDS_NAMES.CATEGORY_ITEM,
  FIELDS_NAMES.GALLERY_ALBUM,
  FIELDS_NAMES.GALLERY_ITEM,
  FIELDS_NAMES.RATING,
  FIELDS_NAMES.PRICE,
  FIELDS_NAMES.NEWS_FILTER,
  FIELDS_NAMES.WEBSITE,
];

const COMMON_FIELDS_AND_CONTACTS = [...COMMON_FIELDS, ...CONTACT_FIELDS];

export const EXPOSED_FIELDS_FOR_OBJECT_TYPE = {
  hashtag: MAIN_FIELDS,
  commodity: COMMON_FIELDS_AND_CONTACTS,
  currency: COMMON_FIELDS_AND_CONTACTS,
  stocks: COMMON_FIELDS_AND_CONTACTS,
  indices: COMMON_FIELDS_AND_CONTACTS,
  app: [...COMMON_FIELDS_AND_CONTACTS, FIELDS_NAMES.WALLET_ADDRESS],
  car: COMMON_FIELDS_AND_CONTACTS,
  test: COMMON_FIELDS_AND_CONTACTS,
  person: [
    ...COMMON_FIELDS_AND_CONTACTS,
    FIELDS_NAMES.WALLET_ADDRESS,
    FIELDS_NAMES.FEATURED,
    FIELDS_NAMES.PRODUCT_ID,
  ],
  currencies: COMMON_FIELDS_AND_CONTACTS,
  crypto: [
    ...MAIN_FIELDS,
    ...MENU_FIELDS_LEGACY,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.NEWS_FILTER,
    FIELDS_NAMES.WEBSITE,
    FIELDS_NAMES.LINK,
    FIELDS_NAMES.CHART_ID,
  ],
  list: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.LIST_ITEM,
    FIELDS_NAMES.SORT_CUSTOM,
    FIELDS_NAMES.CONTENT_VIEW,
  ],
  product: [
    ...COMMON_FIELDS,
    FIELDS_NAMES.PRODUCT_ID,
    FIELDS_NAMES.GROUP_ID,
    FIELDS_NAMES.WEIGHT,
    FIELDS_NAMES.DIMENSIONS,
    FIELDS_NAMES.OPTIONS,
    FIELDS_NAMES.DEPARTMENTS,
    FIELDS_NAMES.MERCHANT,
    FIELDS_NAMES.MANUFACTURER,
    FIELDS_NAMES.BRAND,
    FIELDS_NAMES.FEATURES,
    FIELDS_NAMES.RELATED,
    FIELDS_NAMES.ADD_ON,
    FIELDS_NAMES.SIMILAR,
    FIELDS_NAMES.SALE,
    FIELDS_NAMES.COMPARE_AT_PRICE,
  ],
  drink: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.RATING,
    FIELDS_NAMES.PRICE,
  ],
  place: [
    ...COMMON_FIELDS_AND_CONTACTS,
    FIELDS_NAMES.COMPANY_ID,
    FIELDS_NAMES.WALLET_ADDRESS,
  ],
  business: [
    ...COMMON_FIELDS_AND_CONTACTS,
    FIELDS_NAMES.COMPANY_ID,
    FIELDS_NAMES.WALLET_ADDRESS,
    FIELDS_NAMES.FEATURED,
  ],
  page: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.PAGE_CONTENT,
    FIELDS_NAMES.WEBSITE,
  ],
  service: [
    ...COMMON_FIELDS,
    FIELDS_NAMES.PRODUCT_ID,
    FIELDS_NAMES.GROUP_ID,
    FIELDS_NAMES.OPTIONS,
    FIELDS_NAMES.DEPARTMENTS,
    FIELDS_NAMES.RELATED,
    FIELDS_NAMES.ADD_ON,
    FIELDS_NAMES.SIMILAR,
    FIELDS_NAMES.EMAIL,
    FIELDS_NAMES.PHONE,
    FIELDS_NAMES.LINK,
    FIELDS_NAMES.WORK_TIME,
    FIELDS_NAMES.ADDRESS,
    FIELDS_NAMES.MAP,
    FIELDS_NAMES.COMPANY_ID,
    FIELDS_NAMES.WALLET_ADDRESS,
    FIELDS_NAMES.SALE,
  ],
  company: [
    ...COMMON_FIELDS_AND_CONTACTS,
    FIELDS_NAMES.COMPANY_ID,
    FIELDS_NAMES.WALLET_ADDRESS,
  ],
  organization: [
    ...COMMON_FIELDS_AND_CONTACTS,
    FIELDS_NAMES.COMPANY_ID,
    FIELDS_NAMES.WALLET_ADDRESS,
  ],
  hotel: [...COMMON_FIELDS_AND_CONTACTS, FIELDS_NAMES.COMPANY_ID],
  motel: [...COMMON_FIELDS_AND_CONTACTS, FIELDS_NAMES.COMPANY_ID],
  resort: [...COMMON_FIELDS_AND_CONTACTS, FIELDS_NAMES.COMPANY_ID],
  'b&b': [...COMMON_FIELDS_AND_CONTACTS, FIELDS_NAMES.COMPANY_ID],
  restaurant: [
    ...COMMON_FIELDS_AND_CONTACTS,
    FIELDS_NAMES.COMPANY_ID,
    FIELDS_NAMES.WALLET_ADDRESS,
  ],
  dish: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.RATING,
    FIELDS_NAMES.PRICE,
  ],
  cryptopairs: [...MAIN_FIELDS, FIELDS_NAMES.CHART_ID],
  book: [
    ...COMMON_FIELDS,
    FIELDS_NAMES.PRODUCT_ID,
    FIELDS_NAMES.GROUP_ID,
    FIELDS_NAMES.WEIGHT,
    FIELDS_NAMES.DEPARTMENTS,
    FIELDS_NAMES.DIMENSIONS,
    FIELDS_NAMES.AUTHORS,
    FIELDS_NAMES.PUBLISHER,
    FIELDS_NAMES.PRINT_LENGTH,
    FIELDS_NAMES.RELATED,
    FIELDS_NAMES.ADD_ON,
    FIELDS_NAMES.SIMILAR,
    FIELDS_NAMES.LANGUAGE,
    FIELDS_NAMES.PUBLICATION_DATE,
    FIELDS_NAMES.AGE_RANGE,
    FIELDS_NAMES.OPTIONS,
    FIELDS_NAMES.SALE,
    FIELDS_NAMES.COMPARE_AT_PRICE,
  ],
  widget: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.WIDGET,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.WEBSITE,
  ],
  newsfeed: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.NEWS_FEED,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.WEBSITE,
    FIELDS_NAMES.CONTENT_VIEW,
  ],
  shop: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.WEBSITE,
    FIELDS_NAMES.SHOP_FILTER,
  ],
  affiliate: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.RATING,
    FIELDS_NAMES.AFFILIATE_CODE,
    FIELDS_NAMES.AFFILIATE_BUTTON,
    FIELDS_NAMES.AFFILIATE_URL_TEMPLATE,
    FIELDS_NAMES.AFFILIATE_GEO_AREA,
    FIELDS_NAMES.AFFILIATE_PRODUCT_ID_TYPES,
  ],
  webpage: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.WEB_PAGE,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
  ],
  map: [
    ...MAIN_FIELDS,
    ...MAP_TYPE_FIELDS,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.WEBSITE,
  ],
  link: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.RATING,
    FIELDS_NAMES.URL,
  ],
  recipe: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.RATING,
    FIELDS_NAMES.CALORIES,
    FIELDS_NAMES.BUDGET,
    FIELDS_NAMES.COOKING_TIME,
    FIELDS_NAMES.ADD_ON,
    FIELDS_NAMES.SIMILAR,
    FIELDS_NAMES.FEATURES,
    FIELDS_NAMES.COST,
    FIELDS_NAMES.RECIPE_INGREDIENTS,
    FIELDS_NAMES.PRODUCT_ID,
    FIELDS_NAMES.DEPARTMENTS,
    FIELDS_NAMES.NUTRITION,
  ],
  group: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.WEBSITE,
    FIELDS_NAMES.GROUP_EXPERTISE,
    FIELDS_NAMES.GROUP_FOLLOWERS,
    FIELDS_NAMES.GROUP_FOLLOWING,
    FIELDS_NAMES.GROUP_ADD,
    FIELDS_NAMES.GROUP_EXCLUDE,
    FIELDS_NAMES.GROUP_LAST_ACTIVITY,
  ],
  html: [
    ...MAIN_FIELDS,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.WEBSITE,
    FIELDS_NAMES.HTML_CONTENT,
    FIELDS_NAMES.CONTENT_POSITION,
    FIELDS_NAMES.CONTENT_VIEW,
  ],
};

export const SUPPOSED_UPDATES_BY_TYPE = {
  link: [
    {
      name: 'rating',
      values: ['Safety', 'Value'],
    },
    {
      name: 'tagCategory',
      values: ['Pros', 'Cons'],
      id_path: 'id',
    },
  ],
  recipe: [
    {
      name: 'rating',
      values: ['Rating'],
    },
    {
      name: 'tagCategory',
      values: ['Cuisine', 'Meal Type', 'Diet'],
      id_path: 'id',
    },
  ],
};

export const SUPPOSED_UPDATES_TRANSLATIONS = {
  Books: {
    'en-US': 'Books',
  },
  Category: {
    'en-US': 'Category',
    'ru-RU': 'Категория',
    'af-ZA': 'Kategorie',
    'ar-SA': 'فئة',
    'ca-ES': 'Categoria',
    'cs-CZ': 'Kategorie',
    'da-DK': 'Kategori',
    'de-DE': 'Kategorie',
    'es-ES': 'Categoría',
    'et-EE': 'Kategooria',
    'fil-PH': 'Kategorya',
    'fr-FR': 'Catégorie',
    'hi-IN': 'श्रेणी',
    'hr-HR': 'Kategorija',
    'hu-HU': 'Kategória',
    'id-ID': 'Kategori',
    'it-It': 'Categoria',
    'ja-JP': 'カテゴリー',
    'ko-KR': '범주',
    'ms-MY': 'Kategori',
    'pl-PL': 'Kategoria',
    'pt-BR': 'Categoria',
    'uk-UA': 'Категорія',
    'zh-CN': '类别',
  },
  Commissions: {
    'en-US': 'Commissions',
    'ru-RU': 'Комиссии',
    'af-ZA': 'Kommissies',
    'ar-SA': 'عمولات',
    'ca-ES': 'Comissions',
    'cs-CZ': 'Provize',
    'da-DK': 'Kommissioner',
    'de-DE': 'Kommissionen',
    'es-ES': 'Comisiones',
    'et-EE': 'Komisjonid',
    'fil-PH': 'Komisyon',
    'fr-FR': 'Commissions',
    'hi-IN': 'आयोग',
    'hr-HR': 'Komisije',
    'hu-HU': 'Bizottságok',
    'id-ID': 'Komisi',
    'it-IT': 'Commissioni',
    'ja-JP': 'コミッション',
    'ko-KR': '커미션',
    'ms-MY': 'Suruhanjaya',
    'pl-PL': 'Prowizje',
    'pt-BR': 'Comissões',
    'uk-UA': 'Комісії',
    'zh-CN': '佣金',
  },
  Payments: {
    'en-US': 'Payments',
    'ru-RU': 'Платежи',
    'af-ZA': 'Betalings',
    'ar-SA': 'المدفوعات',
    'ca-ES': 'Pagaments',
    'cs-CZ': 'Platby',
    'da-DK': 'Betalinger',
    'de-DE': 'Zahlungen',
    'es-ES': 'Pagos',
    'et-EE': 'Maksed',
    'fil-PH': 'Mga Bayad',
    'fr-FR': 'Paiements',
    'hi-IN': 'भुगतान',
    'hr-HR': 'Plaćanja',
    'hu-HU': 'Fizetések',
    'id-ID': 'Pembayaran',
    'it-IT': 'Pagamenti',
    'ja-JP': '支払い',
    'ko-KR': '지불',
    'ms-MY': 'Bayaran',
    'pl-PL': 'Płatności',
    'pt-BR': 'Pagamentos',
    'uk-UA': 'Платежі',
    'zh-CN': '付款',
  },
  Platform: {
    'en-US': 'Platform',
    'ru-RU': 'Платформа',
    'af-ZA': 'Platform',
    'ar-SA': 'برنامج',
    'ca-ES': 'Plataforma',
    'cs-CZ': 'Plošina',
    'da-DK': 'Platform',
    'de-DE': 'Plattform',
    'es-ES': 'Plataforma',
    'et-EE': 'Platvorm',
    'fil-PH': 'Platform',
    'fr-FR': 'Plateforme',
    'hi-IN': 'प्लैटफ़ॉर्म',
    'hr-HR': 'Platforma',
    'hu-HU': 'Felület',
    'id-ID': 'Platform',
    'it-It': 'Piattaforma',
    'ja-JP': 'プラットホーム',
    'ko-KR': '플랫폼',
    'ms-MY': 'Platform',
    'pl-PL': 'Platforma',
    'pt-BR': 'Plataforma',
    'uk-UA': 'Платформа',
    'zh-CN': '平台',
  },
  Consensus: {
    'en-US': 'Consensus',
    'ru-RU': 'Согласованность',
    'af-ZA': 'Konsensus',
    'ar-SA': 'إجماع',
    'ca-ES': 'Consens',
    'cs-CZ': 'Konsensus',
    'da-DK': 'Konsensus',
    'de-DE': 'Konsens',
    'es-ES': 'Consenso',
    'et-EE': 'Konsensus',
    'fil-PH': 'Consensus',
    'fr-FR': 'Consensus',
    'hi-IN': 'आम सहमति',
    'hr-HR': 'Konsenzus',
    'hu-HU': 'Konszenzus',
    'id-ID': 'Konsensus',
    'it-It': 'Consenso',
    'ja-JP': 'コンセンサス',
    'ko-KR': '의견 일치',
    'ms-MY': 'Konsensus',
    'pl-PL': 'Zgoda',
    'pt-BR': 'Consenso',
    'uk-UA': 'Узгодженість',
    'zh-CN': '共识',
  },
  Quality: {
    'en-US': 'Quality',
    'ru-RU': 'Качественный',
    'af-ZA': 'Kwaliteit',
    'ar-SA': 'جودة',
    'ca-ES': 'Qualitat',
    'cs-CZ': 'Kvalitní',
    'da-DK': 'Kvalitet',
    'de-DE': 'Qualität',
    'es-ES': 'Calidad',
    'et-EE': 'Kvaliteet',
    'fil-PH': 'Kalidad',
    'fr-FR': 'Qualité',
    'hi-IN': 'गुणवत्ता',
    'hr-HR': 'Kvaliteta',
    'hu-HU': 'Minőség',
    'id-ID': 'Kualitas',
    'it-It': 'Qualità',
    'ja-JP': '品質',
    'ko-KR': '품질',
    'ms-MY': 'Kualiti',
    'pl-PL': 'Jakość',
    'pt-BR': 'Qualidade',
    'uk-UA': 'Якість',
    'zh-CN': '质量',
  },
  Value: {
    'en-US': 'Value',
    'ru-RU': 'Стоимость',
    'af-ZA': 'Waarde',
    'ar-SA': 'قيمة',
    'ca-ES': 'Valor',
    'cs-CZ': 'Hodnota',
    'da-DK': 'Værdi',
    'de-DE': 'Wert',
    'es-ES': 'Valor',
    'et-EE': 'Väärtus',
    'fil-PH': 'Halaga',
    'fr-FR': 'Évaluer',
    'hi-IN': 'मूल्य',
    'hr-HR': 'Vrijednost',
    'hu-HU': 'Érték',
    'id-ID': 'Nilai',
    'it-It': 'Valore',
    'ja-JP': '価値',
    'ko-KR': '값',
    'ms-MY': 'Nilai',
    'pl-PL': 'Wartość',
    'pt-BR': 'Valor',
    'uk-UA': 'Вартість',
    'zh-CN': '价值',
  },
  Pros: {
    'en-US': 'Pros',
    'ru-RU': 'Плюси',
    'af-ZA': 'Voordele',
    'ar-SA': 'الايجابيات',
    'ca-ES': 'Pros',
    'cs-CZ': 'Klady',
    'da-DK': 'Fordele',
    'de-DE': 'Vorteile',
    'es-ES': 'Ventajas',
    'et-EE': 'Profid',
    'fil-PH': 'Pros',
    'fr-FR': 'Avantages',
    'hi-IN': 'पेशेवर',
    'hr-HR': 'Profesionalci',
    'hu-HU': 'Előnyök',
    'id-ID': 'Pro',
    'it-It': 'Aspetti positivi',
    'ja-JP': '長所',
    'ko-KR': '장점',
    'ms-MY': 'Kebaikan',
    'pl-PL': 'Plusy',
    'pt-BR': 'Prós',
    'uk-UA': 'Плюси',
    'zh-CN': '优点',
  },
  Cons: {
    'en-US': 'Cons',
    'ru-RU': 'Минусы',
    'af-ZA': 'Nadele',
    'ar-SA': 'سلبيات',
    'ca-ES': 'Contres',
    'cs-CZ': 'Nevýhody',
    'da-DK': 'Ulemper',
    'de-DE': 'Nachteile',
    'es-ES': 'Contras',
    'et-EE': 'Miinuseid',
    'fil-PH': 'Cons',
    'fr-FR': 'Inconvénients',
    'hi-IN': 'दोष',
    'hr-HR': 'Protiv',
    'hu-HU': 'Hátrányok',
    'id-ID': 'Kontra',
    'it-It': 'Contro',
    'ja-JP': '短所',
    'ko-KR': '단점',
    'ms-MY': 'Keburukan',
    'pl-PL': 'Cons',
    'pt-BR': 'Contra',
    'uk-UA': 'Мінуси',
    'zh-CN': '缺点',
  },
  Presentation: {
    'en-US': 'Presentation',
    'ru-RU': 'Презентация',
    'af-ZA': 'Voorlegging',
    'ar-SA': 'عرض تقديمي',
    'ca-ES': 'Presentació',
    'cs-CZ': 'Prezentace',
    'da-DK': 'Præsentation',
    'de-DE': 'Präsentation',
    'es-ES': 'Presentación',
    'et-EE': 'Esitlus',
    'fil-PH': 'Pagtatanghal',
    'fr-FR': 'Présentation',
    'hi-IN': 'प्रस्तुति',
    'hr-HR': 'Prezentacija',
    'hu-HU': 'Bemutatás',
    'id-ID': 'Presentasi',
    'it-It': 'Presentazione',
    'ja-JP': 'プレゼンテーション',
    'ko-KR': '프레젠테이션',
    'ms-MY': 'Pembentangan',
    'pl-PL': 'Prezentacja',
    'pt-BR': 'Apresentação',
    'uk-UA': 'Презентація',
    'zh-CN': '介绍',
  },
  Taste: {
    'en-US': 'Taste',
    'ru-RU': 'Вкус',
    'af-ZA': 'Smaak',
    'ar-SA': 'المذاق',
    'ca-ES': 'Gust',
    'cs-CZ': 'Chuť',
    'da-DK': 'Smag',
    'de-DE': 'Geschmack',
    'es-ES': 'Gusto',
    'et-EE': 'Maitse',
    'fil-PH': 'Tikman',
    'fr-FR': 'Goûter',
    'hi-IN': 'स्वाद',
    'hr-HR': 'Ukus',
    'hu-HU': 'Íz',
    'id-ID': 'Rasa',
    'it-It': 'Gusto',
    'ja-JP': '味',
    'ko-KR': '맛',
    'ms-MY': 'Rasa',
    'pl-PL': 'Smak',
    'pt-BR': 'Gosto',
    'uk-UA': 'Смак',
    'zh-CN': '品尝',
  },
  Ingredients: {
    'en-US': 'Ingredients',
    'ru-RU': 'Ингредиенты',
    'af-ZA': 'Bestanddele',
    'ar-SA': 'مكونات',
    'ca-ES': 'Ingredients',
    'cs-CZ': 'Přísady',
    'da-DK': 'Ingredienser',
    'de-DE': 'Zutaten',
    'es-ES': 'Ingredientes',
    'et-EE': 'Koostisained',
    'fil-PH': 'Mga sangkap',
    'fr-FR': 'Ingrédients',
    'hi-IN': 'सामग्री',
    'hr-HR': 'Sastojci',
    'hu-HU': 'Hozzávalók',
    'id-ID': 'Bahan',
    'it-It': 'Ingredienti',
    'ja-JP': '材料',
    'ko-KR': '재료',
    'ms-MY': 'Bahan-bahan',
    'pl-PL': 'Składniki',
    'pt-BR': 'Ingredientes',
    'uk-UA': 'Інгредієнти',
    'zh-CN': '原料',
  },
  Overall: {
    'en-US': 'Overall',
    'ru-RU': 'Общее впечатление',
    'af-ZA': 'Algehele',
    'ar-SA': 'شاملة',
    'ca-ES': 'En general',
    'cs-CZ': 'Celkově',
    'da-DK': 'Samlet set',
    'de-DE': 'Gesamt',
    'es-ES': 'General',
    'et-EE': 'Üldiselt',
    'fil-PH': 'Kabuuan',
    'fr-FR': 'Globalement',
    'hi-IN': 'कुल मिलाकर',
    'hr-HR': 'Sve u svemu',
    'hu-HU': 'Átfogó',
    'id-ID': 'Keseluruhan',
    'it-It': 'Complessivamente',
    'ja-JP': '全体',
    'ko-KR': '전반적인',
    'ms-MY': 'Secara keseluruhan',
    'pl-PL': 'Ogólny',
    'pt-BR': 'No geral',
    'uk-UA': 'Загальне враження',
    'zh-CN': '全面的',
  },
  Usability: {
    'en-US': 'Usability',
    'ru-RU': 'Удобство использования',
    'af-ZA': 'Gebruikbaarheid',
    'ar-SA': 'سهولة الاستخدام',
    'ca-ES': 'Usabilitat',
    'cs-CZ': 'Použitelnost',
    'da-DK': 'Anvendelighed',
    'de-DE': 'Benutzerfreundlichkeit',
    'es-ES': 'Usabilidad',
    'et-EE': 'Kasutusmugavus',
    'fil-PH': 'Paggamit',
    'fr-FR': 'Convivialité',
    'hi-IN': 'उपयोगिता',
    'hr-HR': 'Upotrebljivost',
    'hu-HU': 'Használhatóság',
    'id-ID': 'Kegunaan',
    'it-It': 'Usabilità',
    'ja-JP': '「ユーザビリティ」',
    'ko-KR': '사용성',
    'ms-MY': 'Kebolehgunaan',
    'pl-PL': 'Użyteczność',
    'pt-BR': 'Usabilidade',
    'uk-UA': 'Зручність використання',
    'zh-CN': '可用性',
  },
  Accuracy: {
    'en-US': 'Accuracy',
    'ru-RU': 'Точность',
    'af-ZA': 'Akkuraatheid',
    'ar-SA': 'دقة',
    'ca-ES': 'Precisió',
    'cs-CZ': 'Přesnost',
    'da-DK': 'Nøjagtighed',
    'de-DE': 'Genauigkeit',
    'es-ES': 'Precisión',
    'et-EE': 'Täpsus',
    'fil-PH': 'Katumpakan',
    'fr-FR': 'Précision',
    'hi-IN': 'शुद्धता',
    'hr-HR': 'Točnost',
    'hu-HU': 'Pontosság',
    'id-ID': 'Ketepatan',
    'it-It': 'Precisione',
    'ja-JP': '正確さ',
    'ko-KR': '정확성',
    'ms-MY': 'Ketepatan',
    'pl-PL': 'Precyzja',
    'pt-BR': 'Precisão',
    'uk-UA': 'Точність',
    'zh-CN': '准确性',
  },
  Highlights: {
    'en-US': 'Highlights',
    'ru-RU': 'Основные моменты',
    'af-ZA': 'Hoogtepunte',
    'ar-SA': 'يسلط الضوء',
    'ca-ES': 'Destacats',
    'cs-CZ': 'To nejlepší',
    'da-DK': 'Højdepunkter',
    'de-DE': 'Highlights',
    'es-ES': 'Reflejos',
    'et-EE': 'Esiletõstud',
    'fil-PH': 'Mga Highlight',
    'fr-FR': 'Points forts',
    'hi-IN': 'हाइलाइट',
    'hr-HR': 'Naglasci',
    'hu-HU': 'Kiemelések',
    'id-ID': 'Highlight',
    'it-It': 'Mette in risalto',
    'ja-JP': 'ハイライト',
    'ko-KR': '하이라이트',
    'ms-MY': 'Sorotan',
    'pl-PL': 'Pasemka',
    'pt-BR': 'Destaques',
    'uk-UA': 'Основні моменти',
    'zh-CN': '强调',
  },
  Education: {
    'en-US': 'Education',
    'ru-RU': 'Образование',
    'af-ZA': 'Onderwys',
    'ar-SA': 'تعليم',
    'ca-ES': 'Educació',
    'cs-CZ': 'Vzdělání',
    'da-DK': 'Uddannelse',
    'de-DE': 'Ausbildung',
    'es-ES': 'Educación',
    'et-EE': 'Haridus',
    'fil-PH': 'Edukasyon',
    'fr-FR': 'Éducation',
    'hi-IN': 'शिक्षा',
    'hr-HR': 'Obrazovanje',
    'hu-HU': 'Oktatás',
    'id-ID': 'Pendidikan',
    'it-It': 'Formazione scolastica',
    'ja-JP': '教育',
    'ko-KR': '교육',
    'ms-MY': 'Pendidikan',
    'pl-PL': 'Edukacja',
    'pt-BR': 'Educação',
    'uk-UA': 'Освіта',
    'zh-CN': '教育',
  },
  Occupation: {
    'en-US': 'Occupation',
    'ru-RU': 'Занятость',
    'af-ZA': 'Beroep',
    'ar-SA': 'إشغال',
    'ca-ES': 'Ocupació',
    'cs-CZ': 'Obsazení',
    'da-DK': 'Beskæftigelse',
    'de-DE': 'Beruf',
    'es-ES': 'Ocupación',
    'et-EE': 'Amet',
    'fil-PH': 'Trabaho',
    'fr-FR': 'Profession',
    'hi-IN': 'व्यवसाय',
    'hr-HR': 'Okupacija',
    'hu-HU': 'Foglalkozása',
    'id-ID': 'Pekerjaan',
    'it-It': 'Occupazione',
    'ja-JP': '職業',
    'ko-KR': '직업',
    'ms-MY': 'Pekerjaan',
    'pl-PL': 'Zawód',
    'pt-BR': 'Ocupação',
    'uk-UA': 'Зайнятість',
    'zh-CN': '职业',
  },
  Interests: {
    'en-US': 'Interests',
    'ru-RU': 'Интересы',
    'af-ZA': 'Belange',
    'ar-SA': 'الإهتمامات',
    'ca-ES': 'Interessos',
    'cs-CZ': 'Zájmy',
    'da-DK': 'Interesser',
    'de-DE': 'Interessen',
    'es-ES': 'Intereses',
    'et-EE': 'Huvid',
    'fil-PH': 'Mga Interes',
    'fr-FR': 'Intérêts',
    'hi-IN': 'रूचियाँ',
    'hr-HR': 'Interesi',
    'hu-HU': 'Érdeklődés',
    'id-ID': 'Minat',
    'it-It': 'Interessi',
    'ja-JP': '興味',
    'ko-KR': '이해',
    'ms-MY': 'Minat',
    'pl-PL': 'Zainteresowania',
    'pt-BR': 'Interesses',
    'uk-UA': 'Інтереси',
    'zh-CN': '利益',
  },
  Amenities: {
    'en-US': 'Amenities',
    'ru-RU': 'Удобства',
    'af-ZA': 'Geriewe',
    'ar-SA': 'وسائل الراحة',
    'ca-ES': 'Amenitats',
    'cs-CZ': 'Vybavení',
    'da-DK': 'Faciliteter',
    'de-DE': 'Annehmlichkeiten',
    'es-ES': 'Comodidades',
    'et-EE': 'Muudused',
    'fil-PH': 'Amenities',
    'fr-FR': 'Agréments',
    'hi-IN': 'सुविधाएं',
    'hr-HR': 'Pogodnosti',
    'hu-HU': 'Kényelmi szolgáltatások',
    'id-ID': 'Fasilitas',
    'it-It': 'Servizi',
    'ja-JP': 'アメニティ',
    'ko-KR': '예의',
    'ms-MY': 'Kemudahan',
    'pl-PL': 'Udogodnienia',
    'pt-BR': 'Facilidades',
    'uk-UA': 'Зручності',
    'zh-CN': '便利设施',
  },
  Property: {
    'en-US': 'Property',
    'ru-RU': 'Имущество',
    'af-ZA': 'Eiendom',
    'ar-SA': 'ملكية',
    'ca-ES': 'Propietat',
    'cs-CZ': 'Vlastnictví',
    'da-DK': 'Ejendom',
    'de-DE': 'Eigentum',
    'es-ES': 'Propiedad',
    'et-EE': 'Kinnisvara',
    'fil-PH': 'Arian',
    'fr-FR': 'Propriété',
    'hi-IN': 'संपत्ति',
    'hr-HR': 'Imovina',
    'hu-HU': 'Ingatlan',
    'id-ID': 'Properti',
    'it-It': 'Proprietà',
    'ja-JP': '財産',
    'ko-KR': '재산',
    'ms-MY': 'Hartanah',
    'pl-PL': 'Nieruchomość',
    'pt-BR': 'Propriedade',
    'uk-UA': 'Власність',
    'zh-CN': '财产',
  },
  Service: {
    'en-US': 'Service',
    'ru-RU': 'Обслуживание',
    'af-ZA': 'Diens',
    'ar-SA': 'خدمة',
    'ca-ES': 'Servei',
    'cs-CZ': 'Servis',
    'da-DK': 'Service',
    'de-DE': 'Service',
    'es-ES': 'Servicio',
    'et-EE': 'Teenus',
    'fil-PH': 'Serbisyo',
    'fr-FR': 'Service',
    'hi-IN': 'सेवा',
    'hr-HR': 'Servis',
    'hu-HU': 'Szolgáltatás',
    'id-ID': 'Melayani',
    'it-It': 'Servizio',
    'ja-JP': 'サービス',
    'ko-KR': '서비스',
    'ms-MY': 'Perkhidmatan',
    'pl-PL': 'Usługa',
    'pt-BR': 'Serviço',
    'uk-UA': 'Сервіс',
    'zh-CN': '服务',
  },
  Ambience: {
    'en-US': 'Ambience',
    'ru-RU': 'Атмосфера',
    'af-ZA': 'Atmosfeer',
    'ar-SA': 'الجو المحيط',
    'ca-ES': 'Ambient',
    'cs-CZ': 'Prostředí',
    'da-DK': 'Atmosfære',
    'de-DE': 'Ambiente',
    'es-ES': 'Ambiente',
    'et-EE': 'Atmosfäär',
    'fil-PH': 'Ambience',
    'fr-FR': 'Ambiance',
    'hi-IN': 'परिवेश',
    'hr-HR': 'Ambijent',
    'hu-HU': 'Környezet',
    'id-ID': 'Suasana',
    'it-It': 'Ambiente',
    'ja-JP': '雰囲気',
    'ko-KR': '분위기',
    'ms-MY': 'Suasana',
    'pl-PL': 'Atmosfera',
    'pt-BR': 'Ambiente',
    'uk-UA': 'Атмосфера',
    'zh-CN': '环境',
  },
  Food: {
    'en-US': 'Food',
    'ru-RU': 'Еда',
    'af-ZA': 'Kos',
    'ar-SA': 'غذاء',
    'ca-ES': 'Menjar',
    'cs-CZ': 'Jídlo',
    'da-DK': 'Mad',
    'de-DE': 'Essen',
    'es-ES': 'Alimento',
    'et-EE': 'Toit',
    'fil-PH': 'Pagkain',
    'fr-FR': 'Aliments',
    'hi-IN': 'भोजन',
    'hr-HR': 'Hrana',
    'hu-HU': 'Étel',
    'id-ID': 'Makanan',
    'it-It': 'Cibo',
    'ja-JP': '食べ物',
    'ko-KR': '음식',
    'ms-MY': 'Makanan',
    'pl-PL': 'Żywność',
    'pt-BR': 'Comida',
    'uk-UA': 'Їжа',
    'zh-CN': '食物',
  },
  Cuisine: {
    'en-US': 'Cuisine',
    'ru-RU': 'Кухня',
    'af-ZA': 'Kookkuns',
    'ar-SA': 'أطباق',
    'ca-ES': 'Cuina',
    'cs-CZ': 'Kuchyně',
    'da-DK': 'Køkken',
    'de-DE': 'Küche',
    'es-ES': 'Cocina',
    'et-EE': 'Köök',
    'fil-PH': 'Pagluto',
    'fr-FR': 'Cuisine',
    'hi-IN': 'व्यंजन',
    'hr-HR': 'Kuhinja',
    'hu-HU': 'Konyha',
    'id-ID': 'Masakan',
    'it-It': 'Cucina',
    'ja-JP': '料理',
    'ko-KR': '요리',
    'ms-MY': 'Masakan',
    'pl-PL': 'Kuchnia',
    'pt-BR': 'Cozinha',
    'uk-UA': 'Кухня',
    'zh-CN': '美食',
  },
  Features: {
    'en-US': 'Features',
    'ru-RU': 'Особенности',
    'af-ZA': 'Kenmerke',
    'ar-SA': 'سمات',
    'ca-ES': 'Característiques',
    'cs-CZ': 'Funkce',
    'da-DK': 'Funktioner',
    'de-DE': 'Merkmale',
    'es-ES': 'Características',
    'et-EE': 'Funktsioonid',
    'fil-PH': 'Mga Tampok',
    'fr-FR': 'Fonctionnalités',
    'hi-IN': 'विशेषताएँ',
    'hr-HR': 'Značajke',
    'hu-HU': 'Jellemzők',
    'id-ID': 'Fitur',
    'it-It': 'Caratteristiche',
    'ja-JP': '特徴',
    'ko-KR': '특징',
    'ms-MY': 'Ciri-ciri',
    'pl-PL': 'Cechy',
    'pt-BR': 'Características',
    'uk-UA': 'Особливості',
    'zh-CN': '特征',
  },
  'Good For': {
    'en-US': 'Good For',
    'ru-RU': 'Подходит для',
    'af-ZA': 'Goed vir',
    'ar-SA': 'جيدة ل',
    'ca-ES': 'Bo per',
    'cs-CZ': 'Dobré pro',
    'da-DK': 'Godt for',
    'de-DE': 'Gut für',
    'es-ES': 'Bueno para',
    'et-EE': 'Sobib',
    'fil-PH': 'Mabuti para sa',
    'fr-FR': 'Bon pour',
    'hi-IN': 'चलो अच्छा ही हुआ',
    'hr-HR': 'Dobro za',
    'hu-HU': 'Jó arra',
    'id-ID': 'Baik untuk',
    'it-It': 'Buono per',
    'ja-JP': '良い',
    'ko-KR': '좋은',
    'ms-MY': 'Baik untuk',
    'pl-PL': 'Dobre dla',
    'pt-BR': 'Bom para',
    'uk-UA': 'Добре для',
    'zh-CN': '适合',
  },
  Rating: {
    'en-US': 'Rating',
    'ru-RU': 'Рейтинг',
    'af-ZA': 'Gradering',
    'ar-SA': 'تقييم',
    'ca-ES': 'Valoració',
    'cs-CZ': 'Hodnocení',
    'da-DK': 'Bedømmelse',
    'de-DE': 'Bewertung',
    'es-ES': 'Clasificación',
    'et-EE': 'Hinnang',
    'fil-PH': 'Marka',
    'fr-FR': 'Évaluation',
    'hi-IN': 'रेटिंग',
    'hr-HR': 'Ocjena',
    'hu-HU': 'Értékelés',
    'id-ID': 'Peringkat',
    'it-It': 'Valutazione',
    'ja-JP': '評価',
    'ko-KR': '평가',
    'ms-MY': 'Penilaian',
    'pl-PL': 'Ocena',
    'pt-BR': 'Avaliação',
    'uk-UA': 'Рейтинг',
    'zh-CN': '评分',
  },
  Tags: {
    'en-US': 'Tags',
    'ru-RU': 'Теги',
    'af-ZA': 'Tags',
    'ar-SA': 'العلامات',
    'ca-ES': 'Etiquetes',
    'cs-CZ': 'Tagy',
    'da-DK': 'Tags',
    'de-DE': 'Stichworte',
    'es-ES': 'Etiquetas',
    'et-EE': 'Sildid',
    'fil-PH': 'Mga tag',
    'fr-FR': 'Mots clés',
    'hi-IN': 'टैग',
    'hr-HR': 'Oznake',
    'hu-HU': 'Címkék',
    'id-ID': 'Tag',
    'it-It': 'Tag',
    'ja-JP': '「タグ」',
    'ko-KR': '태그',
    'ms-MY': 'Tag',
    'pl-PL': 'Tagi',
    'pt-BR': 'Tag',
    'uk-UA': 'Теги',
    'zh-CN': '标签',
  },
  Safety: {
    'en-US': 'Safety',
    'ru-RU': 'Безопасность',
    'af-ZA': 'Veiligheid',
    'ar-SA': 'السلامة',
    'ca-ES': 'Seguretat',
    'cs-CZ': 'Bezpečnost',
    'da-DK': 'Sikkerhed',
    'de-DE': 'Sicherheit',
    'es-ES': 'Seguridad',
    'et-EE': 'Ohutus',
    'fil-PH': 'Kaligtasan',
    'fr-FR': 'Sécurité',
    'hi-IN': 'सुरक्षा',
    'hr-HR': 'Sigurnost',
    'hu-HU': 'Biztonság',
    'id-ID': 'Keamanan',
    'it-IT': 'Sicurezza',
    'ja-JP': '安全',
    'ko-KR': '안전',
    'ms-MY': 'Keselamatan',
    'pl-PL': 'Bezpieczeństwo',
    'pt-BR': 'Segurança',
    'uk-UA': 'Безпека',
    'zh-CN': '安全',
  },
  'Recipe tags': {
    'en-US': 'Recipe tags',
    'ru-RU': 'Теги рецептов',
    'af-ZA': 'Reseptetikette',
    'ar-SA': 'علامات الوصفات',
    'ca-ES': 'Etiquetes de receptes',
    'cs-CZ': 'Štítky receptů',
    'da-DK': 'Opskriftsmærker',
    'de-DE': 'Rezept-Tags',
    'es-ES': 'Etiquetas de recetas',
    'et-EE': 'Retsepti sildid',
    'fil-PH': 'Mga tag ng resipe',
    'fr-FR': 'Étiquettes de recette',
    'hi-IN': 'रेसिपी टैग',
    'hr-HR': 'Oznake recepata',
    'hu-HU': 'Recept címkék',
    'id-ID': 'Tag resep',
    'it-IT': 'Tag di ricette',
    'ja-JP': 'レシピタグ',
    'ko-KR': '레시피 태그',
    'ms-MY': 'Tag resipi',
    'pl-PL': 'Tagi przepisów',
    'pt-BR': 'Etiquetas de receitas',
    'uk-UA': 'Теги рецептів',
    'zh-CN': '食谱标签',
  },
  'Meal Type': {
    'en-US': 'Meal Type',
    'ru-RU': 'Тип блюда',
    'af-ZA': 'Maaltyd Tipe',
    'ar-SA': 'نوع الوجبة',
    'ca-ES': 'Tipus de menjar',
    'cs-CZ': 'Typ jídla',
    'da-DK': 'Måltidstype',
    'de-DE': 'Art der Mahlzeit',
    'es-ES': 'Tipo de comida',
    'et-EE': 'Toidutüüp',
    'fil-PH': 'Uri ng Pagkain',
    'fr-FR': 'Type de repas',
    'hi-IN': 'भोजन प्रकार',
    'hr-HR': 'Vrsta obroka',
    'hu-HU': 'Étkezési típus',
    'id-ID': 'Jenis Makanan',
    'it-It': 'Tipo di pasto',
    'ja-JP': '食事の種類',
    'ko-KR': '식사 유형',
    'ms-MY': 'Jenis Makanan',
    'pl-PL': 'Rodzaj posiłku',
    'pt-BR': 'Tipo de refeição',
    'uk-UA': 'Тип страви',
    'zh-CN': '餐类',
  },
  Diet: {
    'en-US': 'Diet',
    'ru-RU': 'Диета',
    'af-ZA': 'Dieet',
    'ar-SA': 'حمية',
    'ca-ES': 'Dieta',
    'cs-CZ': 'Dieta',
    'da-DK': 'Diæt',
    'de-DE': 'Diät',
    'es-ES': 'Dieta',
    'et-EE': 'Dieet',
    'fil-PH': 'Diyeta',
    'fr-FR': 'Régime',
    'hi-IN': 'आहार',
    'hr-HR': 'Dijeta',
    'hu-HU': 'Diéta',
    'id-ID': 'Diet',
    'it-It': 'Dieta',
    'ja-JP': '食事制限',
    'ko-KR': '식이요법',
    'ms-MY': 'Diet',
    'pl-PL': 'Dieta',
    'pt-BR': 'Dieta',
    'uk-UA': 'Дієта',
    'zh-CN': '饮食',
  },
} as const;

export const AUTHORITY_FIELD_ENUM = Object.freeze({
  ADMINISTRATIVE: 'administrative',
  OWNERSHIP: 'ownership',
} as const);

export const OBJECT_TYPES_FOR_GROUP_ID = Object.freeze([
  OBJECT_TYPES.PRODUCT,
  OBJECT_TYPES.SERVICE,
  OBJECT_TYPES.BOOK,
] as const);

export const WEIGHT_UNITS = Object.freeze(['kg', 'g', 'lb', 'oz'] as const);

export const DIMENSION_UNITS = Object.freeze(['cm', 'm', 'in', 'ft'] as const);
